### ISSUE TITLE
Error: Directory exists

### ISSUE THREAD

**Issue by Revadike** [website-scraper/node-website-scraper-phantom#3]
I keep getting this error when using this

**Comment by s0ph1e** [comment]
Hi @Royalgamer06 
Looks like you are trying to save to directory which already exists. It is not possible by default. You should use not existing directory or [create custom resourceSaver as described in docs](https://github.com/website-scraper/node-website-scraper#resourcesaver)

**Comment by Revadike** [comment]
Yes, I don't have an existing folder. It works for the first file it scrapes, but after the first file has been saved (and thus the directory created) it starts logging errors.

**Comment by s0ph1e** [comment]
@Royalgamer06 it is expected behavior, not existing directory is required for each `scrape`

It is done in this way to not allow scraper to modify existing files
That's why for first scrape it is ok but for second it returns error

But if you are confident in your code - you can use [resourceSaver](https://github.com/website-scraper/node-website-scraper/tree/v3.3.7#resourcesaver) option to modify this behavior
